### ISSUE TITLE
published 0.0.0

### ISSUE THREAD

**Issue by ralphtheninja** [Level/level-mobile#1]
Just posting this to let people know I have published version `0.0.0` just to steal the name. This is not working for me on linux right now.

**Comment by ralphtheninja** [comment]
```
$ npm owner ls level-mobile
ralphtheninja <ralphtheninja@riseup.net>
rvagg <rod@vagg.org>
juliangruber <julian@juliangruber.com>
obastemur <obastemur@gmail.com>
```

cc @rvagg @juliangruber @obastemur

**Comment by obastemur** [comment]
@ralphtheninja Thanks! I'm going to work on it a.s.a.p to make sure it works.

**Comment by ralphtheninja** [comment]
Also see https://github.com/Level/leveldown-mobile/issues/2
